import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.3';
env.allowLocalModels=false;
const $=s=>document.querySelector(s);const points=[];let running=false,rec=null,extractor=null;
const xp=['嬉しい','悲しい','好き','嫌い','楽しい','怖い','驚き','感動','feel','happy','sad','love'],xn=['思う','考える','理由','なぜ','分析','比較','データ','構造','方法','because','analyze','compare'],yp=['社会','世界','地域','学校','他者','みんな','環境','自然','community','society','world','people'],yn=['私','自分','僕','わたし','経験','気持ち','個人','me','my','myself'];
function lexical(text,pos,neg){let s=0,t=text.toLowerCase();for(const w of pos)if(t.includes(w.toLowerCase()))s++;for(const w of neg)if(t.includes(w.toLowerCase()))s--;return Math.max(-1,Math.min(1,s/3))}function embSig(v,o){let a=0,b=0;for(let i=o;i<v.length;i+=4)a+=v[i];for(let i=o+2;i<v.length;i+=4)b+=v[i];return Math.tanh((a-b)*1.7)}
async function analyze(text){let embedding;try{extractor??=await pipeline('feature-extraction','Xenova/paraphrase-multilingual-MiniLM-L12-v2',{dtype:'q8'});const out=await extractor(text,{pooling:'mean',normalize:true});embedding=Array.from(out.data)}catch{embedding=new Array(64).fill(0);for(let i=0;i<text.length;i++)embedding[(text.charCodeAt(i)+i*17)%64]++;const n=Math.hypot(...embedding)||1;embedding=embedding.map(x=>x/n)}let x=.68*lexical(text,xp,xn)+.32*embSig(embedding,0),y=.68*lexical(text,yp,yn)+.32*embSig(embedding,1);x=Math.max(-1,Math.min(1,x));y=Math.max(-1,Math.min(1,y));return{text,x,y,label:(y>=0?'社会・外界':'個人')+' × '+(x>=0?'感情':'分析')}}
function render(d){points.push(d);let li=document.createElement('li');li.innerHTML=`<b>${d.text.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</b><br><small>${d.label} / x=${d.x.toFixed(2)}, y=${d.y.toFixed(2)}</small>`;$('#transcriptList').prepend(li);$('#latestText').textContent=d.text;$('#latestX').textContent=d.x.toFixed(2);$('#latestY').textContent=d.y.toFixed(2);$('#latestClass').textContent=d.label;draw()}
function draw(){const c=$('#scatter'),ctx=c.getContext('2d'),w=c.width,h=c.height,m=64;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fcfcfb';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#d5d5d5';for(let i=0;i<=10;i++){let x=m+(w-2*m)*i/10,y=m+(h-2*m)*i/10;ctx.beginPath();ctx.moveTo(x,m);ctx.lineTo(x,h-m);ctx.stroke();ctx.beginPath();ctx.moveTo(m,y);ctx.lineTo(w-m,y);ctx.stroke()}ctx.strokeStyle='#222';ctx.beginPath();ctx.moveTo(m,h/2);ctx.lineTo(w-m,h/2);ctx.stroke();ctx.beginPath();ctx.moveTo(w/2,m);ctx.lineTo(w/2,h-m);ctx.stroke();ctx.fillStyle='#555';ctx.font='18px sans-serif';ctx.fillText('分析的',m,36);ctx.fillText('感情的',w-m-56,36);ctx.fillText('社会・外界志向',w/2+10,m-16);ctx.fillText('個人的',w/2+10,h-m+38);for(const [i,p] of points.entries()){let x=m+(p.x+1)/2*(w-2*m),y=h-m-(p.y+1)/2*(h-2*m);ctx.beginPath();ctx.fillStyle='#111';ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.font='13px sans-serif';ctx.fillText(String(i+1),x+10,y-8)}}draw();
$('#startBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('SpeechRecognition APIが利用できません');running=true;rec=new SR();rec.lang=$('#langSelect').value;rec.continuous=true;rec.interimResults=true;rec.onstart=()=>$('#globalStatus').textContent='音声認識中';rec.onresult=async e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript.trim();if(e.results[i].isFinal&&t.length>1){$('#globalStatus').textContent='分析中';render(await analyze(t));$('#globalStatus').textContent='音声認識中'}else interim+=t}$('#interim').textContent=interim||'…'};rec.onend=()=>{if(running){try{rec.start()}catch{}}};rec.start();$('#startBtn').disabled=true;$('#stopBtn').disabled=false};$('#stopBtn').onclick=()=>{running=false;rec?.stop();$('#startBtn').disabled=false;$('#stopBtn').disabled=true;$('#globalStatus').textContent='停止'};$('#clearBtn').onclick=()=>{points.length=0;$('#transcriptList').innerHTML='';$('#interim').textContent='…';draw()};
